"""initial_schema_final

Revision ID: c9f910de22b4
Revises:
Create Date: 2026-06-29 10:30:25.924912

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "c9f910de22b4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
